Repository lspcontainers/dockerfiles, pull requests merged in 2021-05, with the labels that each got.

#2 #1: Adds docker and lua language servers
  docker-langserver/Dockerfile
  lua-language-server/Dockerfile
Labels: enhancement

#5 Add initial support for Go LSP (gopls)
  go-language-server/Dockerfile
Labels: enhancement

#9 #8: Changes from issue #6
  .env
  bash-language-server/Dockerfile
  build.sh
  docker-compose.yml
  docker-langserver/Dockerfile
  go-language-server/Dockerfile
  gopls/Dockerfile
  lua-language-server/Dockerfile
  node_base/Dockerfile
  typescript-language-server/Dockerfile
  yaml-language-server/Dockerfile
Labels: enhancement

#4 Add pyright
  pyright/Dockerfile
Labels: enhancement

#10 #8: Changes from issue #6
  bash-language-server/Dockerfile
  docker-langserver/Dockerfile
  pyright/Dockerfile
  typescript-language-server/Dockerfile
  yaml-language-server/Dockerfile
Labels: enhancement

#11 feat(rust): Add rust language server
  docker-compose.yml
  rust-analyzer/Dockerfile
Labels: enhancement

#16 #15: Organizes Dockerfiles and re-implements docker-compose/env setup
  .env
  Dockerfile
  build.sh
  docker-compose.yaml
  servers/bashls/Dockerfile
  servers/dockerls/Dockerfile
  servers/gopls/Dockerfile
  servers/pyright/Dockerfile
  servers/rust_analyzer/Dockerfile
  servers/sumneko_lua/Dockerfile
  servers/tsserver/Dockerfile
  servers/yamlls/Dockerfile
Labels: enhancement

#19 #18: Implements build matrix and rest of LSP jobs
  .github/workflows/build-image.yml
Labels: enhancement

#21 #20: Adds build-args to Github Actions
  .github/workflows/build-image.yml
Labels: bug

#22 Svelte language server
  .env
  docker-compose.yaml
  servers/svelteserver/Dockerfile
Labels: enhancement

#23 Adding terraform language server
  .env
  docker-compose.yaml
  servers/terraformls/Dockerfile
  servers/terraformls/hashicorp.asc
Labels: enhancement

#3 Python language server
  .env
  .github/workflows/build-image.yml
  docker-compose.yaml
  servers/pyls/Dockerfile
  servers/pyls/README.md
Labels: documentation, enhancement

#24 terraformls - not depend on hashcorp.asc
  servers/terraformls/Dockerfile
  servers/terraformls/hashicorp.asc
Labels: enhancement

#33 feature: adding html language server
  .env
  .github/workflows/build-image.yml
  docker-compose.yaml
  servers/html/Dockerfile
Labels: enhancement

#32 feature: adding Vue Language Server
  .env
  .github/workflows/build-image.yml
  docker-compose.yaml
  servers/vuels/Dockerfile
Labels: enhancement

#30 feature: terraformls 0.17
  .env
  .github/workflows/build-image.yml
Labels: version-bump

#31 feature: adding json ls
  .env
  .github/workflows/build-image.yml
  docker-compose.yaml
  servers/jsonls/Dockerfile
Labels: enhancement

#28 pylsp: Install python3 inside the 2nd container stage
  servers/pylsp/Dockerfile
Labels: enhancement

#26 feat: Adding terraform binary to be able to do formatting
  servers/terraformls/Dockerfile
Labels: enhancement

#29 Do we support compose with the older docker build?
  docker-compose.yaml
Labels: enhancement, question
